### ISSUE TITLE
Threading

### ISSUE THREAD

**Issue by jenniferskay** [kosak/z2kplus#1]
I heard from a reliable source that I can't track the source of threads ... maybe want to think about it sometime

**Comment by kosak** [comment]
I do have (am about to release soonish) a thing that will tell you the immediate "parent" of a message that was a reply to something else. But I ripped out all the threading-qua-threading stuff because I thought no one cared.

Do you think in-reply-to will be good enough?

**Comment by bennetyee** [comment]
that'd work for me.  as long as it doesn't just show the parent message in a popup, but in some way that allows me to follow the in-reply-to pointer chain, click on the timestamp for other messages around the same time for additional context / other replies, etc, i'm good.

**Comment by jenniferskay** [comment]
That sounds great! Parent is all I really want.

**Comment by kosak** [comment]
Initial version released in https://github.com/kosak/z2kplus/pull/27
For follow-on feature requests, kindly open a new ticket.
